#!/usr/bin/make
WGET=wget --continue --no-verbose --show-progress --directory-prefix=cache/downloads/

all: download_extra

clean:
	rm -rf config/includes.chroot/usr/share/xfce4/terminal/colorschemes cache/downloads/xfce4-terminal-colorschemes-1.0
	rm -rf config/includes.chroot/etc/skel/.nano cache/downloads/nanorc-master.zip
	rm -rf config/includes.chroot/usr/share/bleachbit/cleaners cache/downloads/cleanerml-master
	rm -rf config/includes.chroot/etc/firefox-esr/firefox-esr.js cache/downloads/user.js-0.1
	rm -rf config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}
	rm -rf  cache/downloads/sublime_text_3 config/includes.chroot/opt/sublime_text
	rm -f cache/downloads/pidgin-opensteamworks_1.7-buster0-1_amd64.deb
	rm -f cache/downloads/cleanerml-master.zip
	rm -f cache/downloads/lutris_*_all.deb
	rm -f cache/downloads/user.js-0.1.zip
	rm -f cache/downloads/xfce4-terminal-colorschemes-1.0.zip

download_extra: clean
	# Download unpackaged/third-party software
	# TODO file ITPs on bugs.debian.org, package for Debian
	mkdir -p cache/downloads/
	# https://github.com/scopatz/nanorc
	$(WGET) https://github.com/scopatz/nanorc/archive/master.zip -O cache/downloads/nanorc-master.zip
	unzip -q cache/downloads/nanorc-master.zip -d cache/downloads/
	mv cache/downloads/nanorc-master config/includes.chroot/etc/skel/.nano
	git checkout -- config/includes.chroot/etc/skel/.nanorc
	# https://github.com/az0/cleanerml
	$(WGET) https://github.com/az0/cleanerml/archive/master.zip -O cache/downloads/cleanerml-master.zip
	unzip -q cache/downloads/cleanerml-master.zip -d cache/downloads/
	mkdir -p config/includes.chroot/usr/share/bleachbit/cleaners
	mv cache/downloads/cleanerml-master/release/* config/includes.chroot/usr/share/bleachbit/cleaners/
	# https://github.com/nodiscc/user.js
	$(WGET) https://github.com/nodiscc/user.js/archive/0.1.zip -O cache/downloads/user.js-0.1.zip
	unzip -q cache/downloads/user.js-0.1.zip -d cache/downloads/
	mkdir -p config/includes.chroot/etc/firefox-esr
	cd cache/downloads/user.js-0.1/ && make systemwide_user.js
	mv cache/downloads/user.js-0.1/systemwide_user.js config/includes.chroot/etc/firefox-esr/firefox-esr.js
	# https://github.com/EionRobb/pidgin-opensteamworks/
	-mkdir -p config/packages.chroot
	$(WGET) https://gitlab.com/nodiscc/pidgin-opensteamworks/-/jobs/471942010/artifacts/raw/pidgin-opensteamworks_1.7-buster0-1_amd64.deb
	# https://lutris.net/downloads/ - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754129
	$(WGET) https://download.opensuse.org/repositories/home:/strycore/Debian_10/all/lutris_0.5.8.3_all.deb
	# https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/
	# https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/
	mkdir -p config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}
	$(WGET) https://addons.mozilla.org/firefox/downloads/file/3465157/keepassxc_browser-latest-fx.xpi -O config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/keepassxc-browser@keepassxc.org.xpi
	$(WGET) https://addons.mozilla.org/firefox/downloads/file/3530747/cookie_autodelete-3.1.1-an+fx.xpi -O config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/CookieAutoDelete@kennydo.com.xpi
	# https://www.sublimetext.com/ (non-free)
	#$(WGET) https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2
	#tar -C cache/downloads -xvf cache/downloads/sublime_text_3_build_3211_x64.tar.bz2
	#mkdir -p config/includes.chroot/opt
	#mv cache/downloads/sublime_text_3 config/includes.chroot/opt/sublime_text
	# https://github.com/ars3niy/tdlib-purple
	#$(WGET) https://download.opensuse.org/repositories/home:/ars3n1y/Debian_10/amd64/libpurple-telegram-tdlib_0.7.1-1_amd64.deb
