#!/bin/sh

mkdir -p /log/calamares

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
DEFAULT_USER=$(echo $(ls $CHROOT/home) | sed 's|\s.*$||g')

# disable sudo password
rm -rf $CHROOT/etc/sudoers.d/10-installer

# regenerate font cache
chroot $CHROOT sh -c \
    'fc-cache -f -v'

rm -rf \
    $CHROOT/usr/sbin/post-install \
    $CHROOT/usr/sbin/pre-install

if [ -f /usr/sbin/some-postinstall-user-script ]; then
    chroot $CHROOT su $DEFAULT_USER -c \
        "cd /root && sh /usr/sbin/some-postinstall-user-script"
    rm -rf /usr/sbin/some-postinstall-user-script
fi

if [ -f /usr/sbin/some-postinstall-root-script ]; then
    chroot $CHROOT su -c \
        "cd /home/$DEFAULT_USER && sh /usr/sbin/some-postinstall-root-script"
    rm -rf /usr/sbin/some-postinstall-root-script
fi

exit 0
