#!/bin/sh

CHROOT=/target
DEFAULT_USER=$(echo $(ls $CHROOT/home) | sed 's|\s.*$||g')

if [ -d /root/install/filesystem ]; then
    rsync -a /root/install/filesystem/ $CHROOT/
fi

chroot $CHROOT su -c \
    "mkdir -p /var/log/install"
if [ -f $CHROOT/root/install/hooks/post-install.sh ]; then
    chroot $CHROOT su -c \
        "cd / && sh /root/install/hooks/post-install.sh 2>&1 > /var/log/install/post-install.log"
fi
if [ -f $CHROOT/root/install/hooks/user-post-install.sh ]; then
    chroot $CHROOT su $DEFAULT_USER -c \
        "cd /home/$DEFAULT_USER && sh /root/install/hooks/user-post-install.sh 2>&1 > /var/log/install/user-post-install.log"
fi

rm -rf \
    $CHROOT/root/install

exit 0
