#!/bin/sh

mkdir -p /log/calamares

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
DEFAULT_USER=$(echo $(ls $CHROOT/home) | sed 's|\s.*$||g')

# disable sudo password
rm -rf $CHROOT/etc/sudoers.d/10-installer

# regenerate font cache
chroot $CHROOT sh -c \
    'fc-cache -f -v'

rm -rf \
    $CHROOT/usr/sbin/post-install \
    $CHROOT/usr/sbin/pre-install

exit 0
