#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

chroot $CHROOT apt-get update
chroot $CHROOT apt-get install apt-transport-https curl

# brave
chroot $CHROOT sh -c \
    'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
chroot $CHROOT sh -c \
    'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list'

# vscode
chroot $CHROOT sh -c \
    'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg'
chroot $CHROOT sh -c \
    'install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/'
chroot $CHROOT sh -c \
    'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
chroot $CHROOT sh -c \
    'rm -f packages.microsoft.gpg'

chroot $CHROOT apt-get update

exit 0
