#!/bin/sh

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

# rawfs
rsync -a /etc/rawfs/ $CHROOT/

# set default shell
sed -i 's|DSHELL=/bin/bash|DSHELL=/usr/bin/zsh|g'

exit 0
