#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
RELEASE="bullseye"

cat << EOF > $CHROOT/etc/apt/sources.list
# See https://wiki.debian.org/SourcesList for more information.
deb http://deb.debian.org/debian $RELEASE main contrib non-free
deb-src http://deb.debian.org/debian $RELEASE main contrib non-free

deb http://deb.debian.org/debian $RELEASE-updates main contrib non-free
deb-src http://deb.debian.org/debian $RELEASE-updates main contrib non-free

deb http://deb.debian.org/debian/ $RELEASE-backports main contrib non-free
deb-src http://deb.debian.org/debian/ $RELEASE-backports main contrib non-free

# deb http://security.debian.org/debian-security/ $RELEASE-updates main contrib non-free
# deb-src http://security.debian.org/debian-security/ $RELEASE-updates main contrib non-free

deb http://httpredir.debian.org/debian/ sid main contrib non-free
EOF

# brave
chroot $CHROOT sh -c \
    'curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg'
chroot $CHROOT sh -c \
    'echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list'

# vscode
chroot $CHROOT sh -c \
    'wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg'
chroot $CHROOT sh -c \
    'install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/'
chroot $CHROOT sh -c \
    'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
chroot $CHROOT sh -c \
    'rm -f packages.microsoft.gpg'

# install packages
chroot $CHROOT apt-get update
chroot $CHROOT apt-get install -y \
    code
chroot $CHROOT apt-get upgrade -y

exit 0
