#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
RELEASE="bullseye"

cat << EOF > $CHROOT/etc/apt/sources.list
# See https://wiki.debian.org/SourcesList for more information.
deb http://deb.debian.org/debian $RELEASE main contrib non-free
deb-src http://deb.debian.org/debian $RELEASE main contrib non-free

deb http://deb.debian.org/debian $RELEASE-updates main contrib non-free
deb-src http://deb.debian.org/debian $RELEASE-updates main contrib non-free

deb http://deb.debian.org/debian/ $RELEASE-backports main contrib non-free
deb-src http://deb.debian.org/debian/ $RELEASE-backports main contrib non-free

# deb http://security.debian.org/debian-security/ $RELEASE-updates main contrib non-free
# deb-src http://security.debian.org/debian-security/ $RELEASE-updates main contrib non-free
EOF

exit 0
