#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
RELEASE="bullseye"

cat << EOF > $CHROOT/etc/apt/sources.list
deb http://deb.debian.org/debian $RELEASE $RELEASE-updates main contrib
deb-src http://deb.debian.org/debian $RELEASE $RELEASE-updates main contrib

deb http://security.debian.org/debian-security/ $RELEASE-updates main contrib
deb-src http://security.debian.org/debian-security/ $RELEASE-updates main contrib
EOF

exit 0
